# Generated by Django 3.1.6 on 2021-07-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=250)),
                ('ville', models.CharField(max_length=32)),
                ('pays', models.CharField(default='fr', max_length=40)),
                ('code_postale', models.CharField(max_length=32)),
                ('position', models.CharField(default='fr', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateTimeField(auto_now_add=True)),
                ('montant', models.FloatField(default=0.0)),
                ('reference', models.CharField(default='', max_length=5, null=True)),
                ('adherent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhesion.adherent')),
            ],
        ),
    ]
