# Generated by Django 3.1.6 on 2021-07-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='news_letter',
            field=models.BooleanField(default=False),
        ),
    ]
