# Generated by Django 3.1.6 on 2021-07-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0005_auto_20210726_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='position',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='montant',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
