# Generated by Django 3.1.6 on 2021-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneur',
            name='montant',
            field=models.FloatField(default=0.0),
        ),
    ]
