# Generated by Django 3.1.6 on 2021-07-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don', '0003_auto_20210719_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneur',
            name='news_letter',
            field=models.BooleanField(default=False),
        ),
    ]
