# Generated by Django 3.1.6 on 2021-07-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don', '0004_donneur_news_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneur',
            name='vu',
            field=models.BooleanField(default=False),
        ),
    ]
