# Generated by Django 3.1.6 on 2021-07-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don', '0005_donneur_vu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donneur',
            name='vu',
        ),
        migrations.AddField(
            model_name='don',
            name='vu',
            field=models.BooleanField(default=False),
        ),
    ]
