# Generated by Django 3.1.6 on 2021-07-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don', '0006_auto_20210722_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='montant',
            field=models.FloatField(),
        ),
    ]
