# Generated by Django 3.1.1 on 2021-04-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('localisation', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(default=0)),
                ('localisation', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('eco_groupe', models.BooleanField(default=False, null=True)),
                ('abonne', models.ManyToManyField(blank=True, related_name='_profil_abonne_+', to='public_api.Profil')),
                ('abonnement', models.ManyToManyField(blank=True, related_name='_profil_abonnement_+', to='public_api.Profil')),
                ('demande_abonne', models.ManyToManyField(blank=True, related_name='_profil_demande_abonne_+', to='public_api.Profil')),
                ('groupe', models.ManyToManyField(blank=True, to='public_api.Groupe')),
            ],
        ),
    ]
