# Generated by Django 3.1.1 on 2021-04-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='groupe',
        ),
        migrations.AddField(
            model_name='groupe',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public_api.profil'),
        ),
    ]
