# Generated by Django 3.1.1 on 2021-04-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0002_auto_20210418_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='admin',
        ),
        migrations.AddField(
            model_name='groupe',
            name='admin',
            field=models.ManyToManyField(blank=True, to='public_api.Profil'),
        ),
    ]
