# Generated by Django 3.1.1 on 2021-04-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0003_auto_20210418_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembreGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membres', models.ManyToManyField(blank=True, to='public_api.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demande_membre', models.ManyToManyField(blank=True, to='public_api.Profil')),
            ],
        ),
        migrations.AddField(
            model_name='groupe',
            name='demande_membre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public_api.demandegroupe'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='membres',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public_api.membregroupe'),
        ),
    ]
