# Generated by Django 3.1.1 on 2021-09-12 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_api', '0004_auto_20210418_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membregroupe',
            name='membres',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='demande_membre',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='membres',
        ),
        migrations.AddField(
            model_name='groupe',
            name='eco_groupe',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DemandeGroupe',
        ),
        migrations.DeleteModel(
            name='MembreGroupe',
        ),
    ]
