# Generated by Django 3.1.1 on 2021-09-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0005_auto_20210912_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='demande_membre',
            field=models.ManyToManyField(blank=True, related_name='demande_membre', to='public_api.Profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='membre',
            field=models.ManyToManyField(blank=True, related_name='membre', to='public_api.Profil'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='admin', to='public_api.Profil'),
        ),
    ]
