# Generated by Django 3.2.2 on 2021-06-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0065_auto_20210608_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='est_assiette',
            new_name='est_pizza_sauce_special',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='est_crepe_salee',
            new_name='est_salade',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='est_crepe_sucree',
            new_name='est_sandwich',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='est_menu_crepe_salee',
            new_name='est_texmex',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_menu_enfant',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_menu_sandwichs_au_four',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_menu_tacos',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_milkshake',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_pizza_sauce_barbecue',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_salade_pate',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_smoothie',
        ),
    ]
