# Generated by Django 3.2.2 on 2021-06-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0066_auto_20210628_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_supplement',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
