# Generated by Django 3.2.2 on 2021-06-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0067_produit_est_supplement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='est_supplement',
        ),
    ]
