# Generated by Django 3.1.6 on 2021-07-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('journal', models.FileField(blank=True, null=True, upload_to='files/journals')),
                ('text', models.CharField(max_length=2000)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/articles')),
            ],
        ),
    ]
