# Generated by Django 3.1.6 on 2021-07-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal',
            field=models.FileField(blank=True, null=True, upload_to='files/journaux'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='text',
            field=models.CharField(max_length=3000),
        ),
    ]
