# Generated by Django 3.1.6 on 2021-07-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20210716_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date_publication',
            field=models.DateTimeField(),
        ),
    ]
