# Generated by Django 3.1.6 on 2021-06-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0043_auto_20210406_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_restaurant',
            name='disponibilite_livraison',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
