# Generated by Django 3.1.6 on 2021-06-24 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0044_info_restaurant_disponibilite_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulairecontact',
            name='date_message',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 24, 10, 48, 44, 799944)),
        ),
    ]
