# Generated by Django 3.1.6 on 2021-06-24 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0045_formulairecontact_date_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulairecontact',
            name='date_message',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 24, 10, 51, 21, 208770, tzinfo=utc)),
        ),
    ]
