# Generated by Django 3.1.6 on 2021-07-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210712_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, default='', max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/journaux'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=4000),
        ),
    ]
