# Generated by Django 3.1.6 on 2021-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210715_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/articles'),
        ),
    ]
